// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Caseify
{
    internal sealed partial class Vsix
    {
        public const string Id = "Caseify.49bc5385-1fef-4f68-85b8-6616b86d75d2";
        public const string Name = "Caseify";
        public const string Description = @"Transforming or modifying the casing of code elements.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Sailesh B K";
        public const string Tags = "Caseify";
    }
}
