// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Caseify
{
    internal sealed partial class Vsix
    {
        public const string Id = "Caseify.49bc5385-1fef-4f68-85b8-6616b86d75d2";
        public const string Name = "Caseify";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
