// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Caseify
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CaseifyString = "29f0ebde-8a46-405f-8293-772c186239fd";
        public static Guid Caseify = new Guid(CaseifyString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CaseifyMenu = 0x0001;
        public const int CaseifyListGroup = 0x0002;
        public const int CaseifySettings = 0x0003;
        public const int TitleCase = 0x0101;
        public const int CamelCase = 0x0102;
        public const int UpperCase = 0x0103;
        public const int LowerCase = 0x0104;
    }
}